# Generated by Django 5.1.2 on 2024-11-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisoalumno',
            name='aviso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_alumno', to='avisos.aviso'),
        ),
    ]
