# Generated by Django 5.1.3 on 2024-11-21 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_asignatura_profesor'),
        ('asistencia', '0001_initial'),
        ('usuarios', '0002_alter_perfil_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_alumno', to='usuarios.perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('alumno', 'asignatura', 'fecha')},
        ),
    ]
