# Generated by Django 5.1.2 on 2024-11-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('profesor', 'Profesor'), ('apoderado', 'Apoderado'), ('alumno', 'Alumno')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('segundo_rol', models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('profesor', 'Profesor'), ('apoderado', 'Apoderado'), ('alumno', 'Alumno')], default='', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.apoderado')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
    ]
