# Generated by Django 5.1.2 on 2024-11-17 18:59

import django.core.validators
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_rut', message='Formato de RUT inválido. Debe ser como 12345678-9', regex='^[0-9]{7,8}-[0-9Kk]$'), usuarios.models.validar_rut]),
        ),
    ]
