# Generated by Django 5.1.3 on 2024-11-23 19:16

import usuarios.models
from django.db import migrations, models

def add_default_profile_image(apps, schema_editor):
    Perfil = apps.get_model('usuarios', 'Perfil')
    for perfil in Perfil.objects.all():
        if not perfil.foto:
            perfil.save()  # Esto aplicará la imagen por defecto

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_rut'),
    ]

    operations = [
        migrations.RunPython(add_default_profile_image),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default=usuarios.models.default_profile_image, null=True, upload_to='fotos_perfil'),
        ),
    ]
