# Generated by Django 5.1.2 on 2024-11-23 18:36

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='telefono',
            field=models.CharField(max_length=13, validators=[usuarios.models.validate_chilean_phone_number]),
        ),
    ]
