# Generated by Django 5.1.2 on 2024-11-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_apoderado_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='segundo_rol',
        ),
    ]
