# Generated by Django 5.1.2 on 2024-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
    ]
