# Generated by Django 5.1.2 on 2024-11-05 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
        ('evaluacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion'),
            preserve_default=False,
        ),
    ]
