# Generated by Django 5.1.2 on 2024-11-17 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sala',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_sala', message='Solo se permiten números y letras', regex='^[0-9a-zA-Z]*$')]),
        ),
    ]
